### ISSUE TITLE
Caused by: com.nabla.sdk.core.data.exception.WrappedOkhttpInterceptorException: 

### ISSUE THREAD

**Issue by velu-deepholistics** [nabla/nabla-android#8]
Caused by: com.nabla.sdk.core.data.exception.WrappedOkhttpInterceptorException: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
		at com.nabla.sdk.core.data.auth.AuthorizationInterceptor$intercept$updatedRequest$freshAccessToken$1.invokeSuspend(Unknown Source:76)
		at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:10)
		at f50.w0.run(Unknown Source:123)
		at f50.f1.d2(Unknown Source:79)
		at f50.g.L0(Unknown Source:23)
		at f50.j.a(Unknown Source:76)
		at f50.i.e(Unknown Source:0)
		at f50.j.b(Unknown Source:6)
		at f50.i.f(Unknown Source:0)
		at com.nabla.sdk.core.data.auth.AuthorizationInterceptor.intercept(Unknown Source:108)
		at j60.g.a(Unknown Source:166)
		at com.nabla.sdk.core.data.auth.AcceptLanguageInterceptor.intercept(Unknown Source:36)
		at j60.g.a(Unknown Source:166)
		at i60.h.s(Unknown Source:116)
		at i60.h.execute(Unknown Source:27)
		at s8.a.a(Unknown Source:90)
		... 31 more
	Caused by: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
		at kj.a.e(Unknown Source:40)
		at kj.a.<init>(SourceFile:2)
		at com.auth0.android.jwt.c$b.<init>(Unknown Source:2)
		at com.auth0.android.jwt.c.c(Unknown Source:6)
		at com.auth0.android.jwt.c.<init>(Unknown Source:3)
		at com.nabla.sdk.core.data.auth.SessionClientImpl.getFreshAccessTokenUnsafe(Unknown Source:138)
		at com.nabla.sdk.core.data.auth.SessionClientImpl.getFreshAccessToken(Unknown Source:105)
		at du.j.a(Unknown Source:7)
		at com.nabla.sdk.core.data.auth.AuthorizationInterceptor$intercept$updatedRequest$freshAccessToken$1.invokeSuspend(Unknown Source:44)
		... 46 more
	[CIRCULAR REFERENCE:com.apollographql.apollo3.exception.ApolloNetworkException: Failed to execute GraphQL http network request]
	
	
	Nabla Chat is not working in Release build. We are using R8. What could be the possible issue?

**Comment by benoitletondor** [comment]
I tried to reproduce and couldn't, I believe the error you posted is not the first one so the original exception probably has more details but it shouldn't be related to R8, probably a setup or network issue.

Let me know if I missed something.
